apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  user: YWRtaW4=
  password: cXVpZXRqdWxpYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  secret: Ml5mKzNAdjcgLWkgfi8uc3NoL2lkX3JzYSBlYzItdXNlckAzNS4xNzguMzAuMjI4KTMtMXQkKXRscCt4bTE3PSpnKSlfeG9pJiY5bSMyYSY=
